name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ 'src/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'src/**' ]
    
# 環境にあわせて修正してください。
env:
  # ソースファイルのあるフォルダ
  SOURCE_FOLDER: src
  # set this to the dot net version to use
  DOTNET_VERSION: '5.0.x'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.SOURCE_FOLDER}}

    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.SOURCE_FOLDER}}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.SOURCE_FOLDER}}
